[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.liccheck]
authorized_licenses = [
    "bsd",
    "apache 2.0",
    "Apache License 2.0",
    "apache software",
    "isc license (iscl)",
    "mozilla public license 2.0 (mpl 2.0)",
    "mit",
    "python software foundation",
]
